site_name: PlotlyJS.jl
site_description: Julia + plotly.js
site_author: Spencer Lyon
theme_dir: 'docs/theme'

repo_url: https://github.com/spencerlyon2/PlotlyJS.jl

pages:
- Home: index.md
- User Guide:
    - Preliminaries: basics.md
    - Building Blocks: building_traces_layouts.md
    - Putting it together: syncplots.md
    - Working with plots: manipulating_plots.md
    - Contributing: contributing.md
- Examples:
    - examples/3d.md
    - examples/area.md
    - examples/contour.md
    - examples/histograms.md
    - examples/line_scatter.md
    - examples/maps.md
    - examples/subplots.md
    - examples/shapes.md

markdown_extensions:
    - codehilite
    - toc:
        permalink: Â¶
    - admonition

google_analytics: ['UA-36732392-3', 'auto']

extra:
  version: '0.3.2'
  author:
    github: 'spencerlyon2'
extra_css: [css/github.css]
extra_javascript: ["https://cdn.plot.ly/plotly-latest.min.js"]

copyright: Copyright &copy; 2016 <a href="http://spencerlyon.com/">Spencer Lyon</a>
